language: python
python:
  - "3.6"
sudo: false
cache:
  packages: yes
  directories:
    - $HOME/bin
services:
  - docker
before_install:
  - docker pull rocker/verse
  - ./build-docker.sh

after_success:
  - ./deploy-github.sh
