language: python
pandoc_version: 2.0.6
sudo: false
cache:
  packages: yes
  directories:
    - $HOME/bin
services:
  - docker
before_script:
  - ./build-docker.sh
after_success:
  - ./deploy-github.sh
