language: r
pandoc_version: 2.0.6
sudo: false
cache:
  packages: yes
  directories:
    - $HOME/bin

before_install:
  - Rscript -e "update.packages(.libPaths()[1], ask = FALSE)"
before_script:
  - ./build.sh
after_success:
  - ./deploy-github.sh
